version: '3'

services:
  todosDB:
    image: postgres:15.3
    container_name: todos-db
    restart: always
    ports:
      - 5433:5433
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      # - POSTGRES_HOST_AUTH_METHOD= trust
    volumes:
      - ./postgres:/var/lib/postgresql/data
# environment:
#             - REDIS_HOST=redis
#             - REDIS_PORT=6379
#             - PGUSER=postgres
#             - PGHOST=postgres
#             - PGDATABASE=postgres
#             - PGPASSWORD=postgres
#             - PGPORT=5432
